import os

# QDRANT
QDRANT_URL = os.getenv("QDRANT_URL")
QDRANT_COLLECTION_NAME = os.getenv("QDRANT_COLLECTION_NAME")

# EMBEDDINGS / CONTEXT RAG
EMBEDDING_MODEL_NAME = os.getenv(
    "EMBEDDING_MODEL_NAME",
    "intfloat/multilingual-e5-large",
)
CONTEXT_EXPORT_TOP_K = int(os.getenv("CONTEXT_EXPORT_TOP_K", "8"))
CONTEXT_UPGRADE_INPUT_ROOT = os.getenv(
    "CONTEXT_UPGRADE_INPUT_ROOT",
    "/suite/context/input",
)
CONTEXT_UPGRADE_BACKUP_ROOT = os.getenv(
    "CONTEXT_UPGRADE_BACKUP_ROOT",
    "/suite/context/backup",
)
CONTEXT_UPGRADE_SUITE_CONTEXT_ROOT = os.getenv(
    "CONTEXT_UPGRADE_SUITE_CONTEXT_ROOT",
    "/suite/context",
)
CONTEXT_UPGRADE_PROJECT_ROOT = os.getenv(
    "CONTEXT_UPGRADE_PROJECT_ROOT",
    "/suite",
)

# DOCUMENTATION
DOCUMENTATION_EXPORT_TOP_K = 8
DOCUMENTATION_UPGRADE_BACKUP_ROOT = os.getenv(
    "DOCUMENTATION_UPGRADE_BACKUP_ROOT",
    "/suite/context/backup",
)
DOCUMENTATION_UPGRADE_INPUT_ROOT = os.getenv(
    "DOCUMENTATION_UPGRADE_INPUT_ROOT",
    "/suite/context/documentation/input",
)
DOCUMENTATION_UPGRADE_DOCUMENTATION_ROOT = os.getenv(
    "DOCUMENTATION_UPGRADE_DOCUMENTATION_ROOT",
    "/suite/context/documentation",
)

# COHERE
COHERE_API_KEY = os.getenv("COHERE_API_KEY")
COHERE_MODEL = os.getenv("COHERE_MODEL")

# CONFLUENCE
CONFLUENCE_BASE_URL = os.getenv("CONFLUENCE_BASE_URL")
CONFLUENCE_EMAIL = os.getenv("CONFLUENCE_EMAIL")
CONFLUENCE_API_TOKEN = os.getenv("CONFLUENCE_API_TOKEN")
CONFLUENCE_SPACE_KEY = os.getenv("CONFLUENCE_SPACE_KEY")
CONFLUENCE_EXCLUDED_TITLES = os.getenv("CONFLUENCE_EXCLUDED_TITLES", "")

# SLACK
SLACK_BOT_TOKEN = os.getenv("SLACK_BOT_TOKEN")
SLACK_SIGNING_SECRET = os.getenv("SLACK_SIGNING_SECRET")

# SCHEDULER
CONFLUENCE_SYNC_INTERVAL_MINUTES = int(os.getenv("CONFLUENCE_SYNC_INTERVAL_MINUTES", "5"))
