services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    volumes:
      - ./backend:/app
      - ../../context:/suite/context
      - ../../dp/DP-API:/suite/dp/DP-API
      - ../SBM-API:/suite/sbm/SBM-API
      - .:/suite/sbm/sbm-ai-assistant
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
